spring:
  config:
    import: classpath:application-secrets.yml # This is a locally stored file you can find in the private discord server, only contains postgres URL, Username and Password
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect